version: '3.9'

services:
  app:
    image: salahm2002/project2-hotel-management-system-image:latest
    ports:
      - "8081:8080"
    depends_on:
      - database
  database:
    image: mysql:8
    environment:
      MYSQL_DATABASE: webfinalproject
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    ports:
      - "127.0.0.1:3307:3306"
